[package]
name = "circle"
version = "0.0.1"
authors = ["Vladimir Petrigo <taenaru@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
num = "0.2"
